htl_immobilier_homepage:
    path:     /
    defaults: { _controller: HTLImmobilierBundle:Default:index }
accueil:
    path:     /accueil
    defaults: { _controller: HTLImmobilierBundle:Reservation:accueil }
search:
    path:     /front/bien/search
    defaults: { _controller: HTLImmobilierBundle:Front:searchBien }
reserver:
    path:     /front/bien/
    defaults: { _controller: HTLImmobilierBundle:Front:reserverBien }
index:
    path:     /front/bien/index
    defaults: { _controller: HTLImmobilierBundle:Front:index }
listebien:
    path:     /front/bien/listebien
    defaults: { _controller: HTLImmobilierBundle:Front:listeBien }
searchprix:
    path:     /front/bien/prix
    defaults: { _controller: HTLImmobilierBundle:Front:searchPrix}
searchtype:
    path:     /front/bien/type
    defaults: { _controller: HTLImmobilierBundle:Front:searchTypebien }
searchlocalite:
    path:     /front/bien/localite
    defaults: { _controller: HTLImmobilierBundle:Front:searchLocalite }
listeadmin:
    path:     /front/bien/admin
    defaults: { _controller: HTLImmobilierBundle:Front:listeAdmin }
listelocalite:
    path:     /front/bien/charger
    defaults: { _controller: HTLImmobilierBundle:Front:listelocalite }
listereservation:
    path:     /front/bien/reservation
    defaults: { _controller: HTLImmobilierBundle:Front:listeReservation }
details:
    path:     /front/bien/details{id}
    defaults: { _controller: HTLImmobilierBundle:Front:detailsReservation }
    requirements:
        id: \d+
